name: ffi_gen
description: FFI bindings generator (prototype)

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  source_gen: ^0.9.5
  meta: ^1.1.8
  path: ^1.6.4
  libclang:
    path: libclang/

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
